version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: react_wagtail_app_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=wagtail_dev
      - POSTGRES_USER=wagtail_dev
      - POSTGRES_PASSWORD=wagtail_dev

  frontend:
    build:
      context: ./frontend
      dockerfile: ../compose/local/react/Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - REACT_APP_API_URL=http://web:8000
    stdin_open: true
    tty: true
    depends_on:
      - web

volumes:
  postgres_data:
